function(ParseArchiveDependency)
    GetJSON(JSON url url)
    if(NOT url)
        message(WARNING [[Missing property "url"]])
        FAIL()
        return()
    endif()

    set(FROM "${DEPENDENCY_DIR}/.EXTRACTED")
    cmake_path(GET url FILENAME archive_file)
    set(archive_destination "${DEPENDENCY_ROOT}/${archive_file}")
    
    # Verify cache
    if(NOT EXISTS "${FROM}")
        if(EXISTS "${DEPENDENCY_DIR}")
            Uninstall()
        endif()

        _Update()
    else()
        #Check if update is required
        file(READ "${FROM}" archive_file_cached)
        if(NOT archive_file_cached STREQUAL archive_file)
            Uninstall()    
            _Update()
        endif()
    endif()
endfunction()

## Helpers ######################################################
macro(_Update)
    Verify(is)
    if(is)
        _Extract()
    else()
        file(REMOVE "${archive_destination}")
        _Download()
        _Extract()
    endif()
endmacro()

macro(_Extract)
    set(DEPENDENCY_DIR_TMP "${DEPENDENCY_DIR}.tmp")
    Extract(archive_destination DEPENDENCY_DIR_TMP)

    # Check flatness
    file(GLOB archive_content RELATIVE "${DEPENDENCY_DIR_TMP}" "${DEPENDENCY_DIR_TMP}/*")
    list(LENGTH archive_content is_flat)
    if( is_flat EQUAL 1
    AND IS_DIRECTORY "${DEPENDENCY_DIR_TMP}/${archive_content}")
        # archive contains content in a single top-level directory
        file(RENAME "${DEPENDENCY_DIR_TMP}/${archive_content}" "${DEPENDENCY_DIR}")
        file(REMOVE_RECURSE "${DEPENDENCY_DIR_TMP}")
    else()
        # archive is flat
        file(RENAME "${DEPENDENCY_DIR_TMP}" "${DEPENDENCY_DIR}")
    endif()

    file(WRITE "${FROM}" "${archive_file}")
    PREPARE_PATCH()
endmacro()

macro(_Download)
    Download("${url}" "${archive_destination}" result)
    list(GET result 1 error)
    list(GET result 0 result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${error}")
        return()
    endif()
endmacro()

macro(Verify output)
    if(NOT EXISTS "${archive_destination}")
        set(${output} FALSE)
    else()
        GetJSON(JSON sha256 sha256)
        if(sha256)
            EQUALS_SHA256(archive_destination sha256 same)
            if(same)
                set(${output} TRUE)
            else()
                message(WARNING "Hash of ${archive_file} did not match ${sha256}")
                set(${output} FALSE)
            endif()
        else()
            set(${output} TRUE)
        endif()
    endif()
endmacro()
