macro(SetupVScode)
if (CMAKE_CXX_COMPILER_ID MATCHES Clang)
    Configure(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/lldb/.vscode/launch.json ${CMAKE_CURRENT_SOURCE_DIR}/.vscode/launch.json)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL GNU)
    Configure(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/gdb/.vscode/launch.json ${CMAKE_CURRENT_SOURCE_DIR}/.vscode/launch.json)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL MSVC)
    Configure(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/vsdbg/.vscode/launch.json ${CMAKE_CURRENT_SOURCE_DIR}/.vscode/launch.json)
endif() 
endmacro()

function(Finalize)
    if($ENV{VSCODE_CLI})
        SetupVScode()
    endif()
endfunction()

cmake_language(DEFER CALL Finalize)
