function(TargetName target outVar)
    get_target_property(name ${target} OUTPUT_NAME)

    if(name STREQUAL "name-NOTFOUND")
        set(${outVar} ${target} PARENT_SCOPE)
    else()
        set(${outVar} ${name} PARENT_SCOPE)
    endif()
endfunction()

function(TargetPrefix target outVar)
    get_target_property(type ${target} TYPE)

    if(type STREQUAL EXECUTABLE)
        set(default "")
    elseif(type STREQUAL SHARED_LIBRARY)
        set(default ${CMAKE_SHARED_LIBRARY_PREFIX})
    elseif(type STREQUAL MODULE_LIBRARY)
        set(default ${CMAKE_SHARED_MODULE_PREFIX})
    elseif(type STREQUAL STATIC_LIBRARY)
        set(default ${CMAKE_STATIC_LIBRARY_PREFIX})
    else()
        message(FATAL_ERROR "Unsupported Target Type")
    endif()

    get_target_property(prefix ${target} PREFIX)
    if(prefix STREQUAL "prefix-NOTFOUND")
        set(${outVar} ${default} PARENT_SCOPE)
    else()
        set(${outVar} ${prefix} PARENT_SCOPE)
    endif()
endfunction()

function(TargetSuffix target outVar)
    get_target_property(type ${target} TYPE)

    if(type STREQUAL EXECUTABLE)
        set(default ${CMAKE_EXECUTABLE_SUFFIX})
    elseif(type STREQUAL SHARED_LIBRARY)
        set(default ${CMAKE_SHARED_LIBRARY_SUFFIX})
    elseif(type STREQUAL MODULE_LIBRARY)
        set(default ${CMAKE_SHARED_MODULE_SUFFIX})
    elseif(type STREQUAL STATIC_LIBRARY)
        set(default ${CMAKE_STATIC_LIBRARY_SUFFIX})
    else()
        message(FATAL_ERROR "Unsupported Target Type")
    endif()

    get_target_property(suffix ${target} SUFFIX)
    
    if(suffix STREQUAL "suffix-NOTFOUND")
        set(${outVar} ${default} PARENT_SCOPE)
    else()
        set(${outVar} ${suffix} PARENT_SCOPE)
    endif()
endfunction()

function(OutputName target outVar)
    TargetName(${target} name)
    TargetPrefix(${target} prefix)
    TargetSuffix(${target} suffix)
    set(${outVar} ${prefix}${name}${suffix} PARENT_SCOPE)
endfunction()
