# PROJECT_ROOT
get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

# ./
if(WIN32)
    set(./ "")
else()
    set(./ ./)
endif()

# CMAKE_IN_TRY_COMPILE
if(${PROJECT_NAME} STREQUAL CMAKE_TRY_COMPILE)
    set(CMAKE_IN_TRY_COMPILE TRUE)
else()
    set(CMAKE_IN_TRY_COMPILE FALSE)
endif()

# DOTCMAKE_HOST_IS_64BIT
cmake_host_system_information(RESULT DOTCMAKE_HOST_IS_64BIT QUERY IS_64BIT)
# DOTCMAKE_HOST_ARCH
string(TOLOWER ${CMAKE_HOST_SYSTEM_PROCESSOR} DOTCMAKE_HOST_ARCH)

# DOTCMAKE_HOST_IS_ARM
if(DOTCMAKE_HOST_ARCH MATCHES [[^(arm|aarch64)]])
    set(DOTCMAKE_HOST_IS_ARM TRUE)
else()
    set(DOTCMAKE_HOST_IS_ARM FALSE)
endif()
