name: macOS llvm clang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  call-build:
    name: Build
    uses: ./.github/workflows/.cmake.yaml
    with:
      os: macos
